var Enum = require('enum');
var Event = require('../models/Event');
var Tier = require('../models/Tier');

module.exports.EVENTS_TYPES = new Enum([
    "Multiplayer",
    "Hot Pursuit",
    "Race",
    "Interceptor",
    "Duel",
    "Gauntlet",
    "Preview",
    "Rapid Response",
    "Time Trial",
    "Multiplayer",
    "Unknown"
]);

module.exports.EVENTS_TIERS = new Enum([
    "Hyper",
    "Exotic",
    "Super",
    "Performance",
    "Sports",
    "Special Response",
    "Speed Enforcement",
    "Rapid Deployment",
    "Highway Patrol",
    "Traffic Police",
    "Any"
]);

module.exports.EVENTS_PLAYERS = new Enum([
    "Racer",
    "Police",
    "Both"
]);

module.exports.EVENTS_MP = [
    new Event("Arms Race", "Rockingham Point", 22.8, "Multiplayer"),
    new Event("Blacklisted", "East Gorge Canyon", 19.1, "Multiplayer"),
    new Event("Calm Before the Storm", "East Gorge Canyon", 26.5, "Multiplayer"),
    new Event("Charged Attack", "Oakmont Valley", 24.7, "Multiplayer"),
    new Event("Close Call", "Carson Ridge Reservoir", 17.2, "Multiplayer"),
    new Event("Coast To Coast", "Oakmont Valley", 19.8, "Multiplayer"),
    new Event("Complete Control", "Eagle Crest", 14.7, "Multiplayer"),
    new Event("Cut To The Chase", "Grand Ocean Coast", 18.9, "Multiplayer"),
    new Event("Dark Horse", "Carson Ridge Reservoir", 12.0, "Multiplayer"),
    new Event("Dust Storm", "Memorial Valley", 19.3, "Multiplayer"),
    new Event("End Of The Line", "Memorial Valley", 26.7, "Multiplayer"),
    new Event("Escape To The Beach", "Mission Beach", 16.0, "Multiplayer"),
    new Event("Extreme Truth", "Fox Lair Pass", 10.9, "Multiplayer"),
    new Event("Fight Or Flight", "Rockingham Point", 23.3, "Multiplayer"),
    new Event("First Offence", "Big Timber Forest", 12.3, "Multiplayer"),
    new Event("Future Perfect", "Grand Ocean Coast", 12.2, "Multiplayer"),
    new Event("Highway Battle", "Oakmont Valley", 24.0, "Multiplayer"),
    new Event("Hit The Beach", "Boulder Desert", 17.4, "Multiplayer"),
    new Event("Into The Fire", "Fox Lair Pass", 11.5, "Multiplayer"),
    new Event("Lakeside Dream", "Rockingham Point", 17.7, "Multiplayer"),
    new Event("Law And Disorder", "Coral Bay", 17.1, "Multiplayer"),
    new Event("Midnight Run", "Big Timber Forest", 10.6, "Multiplayer"),
    new Event("No Substitute", "Memorial Valley", 12.1, "Multiplayer"),
    new Event("Ocean Blue", "Grand Ocean Coast", 20.7, "Multiplayer"),
    new Event("Pedal To The Metal", "Boulder Desert", 12.9, "Multiplayer"),
    new Event("Porsche Patrol", "Memorial Valley", 18.6, "Multiplayer"),
    new Event("Razor's Edge", "Carson Ridge Reservoir", 17.0, "Multiplayer"),
    new Event("Roadsters Reborn", "Grand Ocean Coast", 13.6, "Multiplayer"),
    new Event("Run To The Hills", "Fox Lair Pass", 18.4, "Multiplayer"),
    new Event("Sand Timer", "Mission Beach", 18.0, "Multiplayer"),
    new Event("Self Preservation", "Mission Beach", 17.8, "Multiplayer"),
    new Event("Shock And Awe", "Boulder Desert", 17.1, "Multiplayer"),
    new Event("Slide Show", "Coral Bay", 12.6, "Multiplayer"),
    new Event("Snake Pit", "Rockingham Point", 22.0, "Multiplayer"),
    new Event("Snowblind", "Eagle Crest", 19.9, "Multiplayer"),
    new Event("Spirit Of Performance", "Carson Ridge Reservoir", 10.7, "Multiplayer"),
    new Event("Summit Assault", "Eagle Crest", 20.0, "Multiplayer"),
    new Event("Sun, Sand And Supercars", "Boulder Desert", 18.3, "Multiplayer"),
    new Event("Tough Justice", "Eagle Crest", 20.2, "Multiplayer"),
    new Event("Untouchable", "East Gorge Canyon", 18.4, "Multiplayer"),
];

module.exports.EVENTS_SP = [
    new Event("Against All Odds", "Grand Ocean Coast", 20.28, "Hot Pursuit", new Tier("Exotic", "Racer")),
    new Event("Arms Race", "Rockhingam Point", 22.69, "Hot Pursuit", new Tier("Speed Enforcement", "Police")),
    new Event("Avalanche", "Fox Lair Pass", 19.79, "Hot Pursuit", new Tier("Super", "Racer")),
    new Event("Beauty and the Beasts", "Mission Beach", 10.3, "Hot Pursuit", new Tier("Performance", "Racer")),
    new Event("Blacklisted", "Eagle Crest", 19.15, "Hot Pursuit", new Tier("Super", "Racer")),
    new Event("Breach of the Peace", "Memorial Valley", 12.07, "Hot Pursuit", new Tier("Sports", "Racer")),
    new Event("Breaking Point", "Coral Bay", 21.89, "Hot Pursuit", new Tier("Hyper", "Racer")),
    new Event("Calm Before the Storm", "East Gorge Canyon", 19.31, "Hot Pursuit", new Tier("Hyper", "Racer")),
    new Event("Charged Attack", "East Gorge Canyon", 24.62, "Hot Pursuit", new Tier("Speed Enforcement", "Police")),
    new Event("Dark Horse", "Carson Ridge Reservoir", 12.07, "Hot Pursuit", new Tier("Traffic Police", "Police")),
    new Event("Double Jeopardy", "Memorial Valley", 26.72, "Hot Pursuit", new Tier("Exotic", "Racer")),
    new Event("Dust Storm", "Memorial Valley", 19.31, "Hot Pursuit", new Tier("Speed Enforcement", "Police")),
    new Event("End of the Line", "Memorial Valley", 26.72, "Hot Pursuit", new Tier("Special Response", "Police")),
    new Event("Escape to the Beach", "Mission Beach", 15.93, "Hot Pursuit", new Tier("Traffic Police", "Police")),
    new Event("Escape Lane", "East Gorge Canyon", 18.51, "Hot Pursuit", new Tier("Performance", "Racer")),
    new Event("Fight or Flight", "Rockhingam Point", 23.34, "Hot Pursuit", new Tier("Special Response", "Police")),
    new Event("First Offence", "Eagle Crest", 12.23, "Hot Pursuit", new Tier("Sports", "Racer")),
    new Event("Hard Target", "Grand Ocean Coast", 19.31, "Hot Pursuit", new Tier("Special Response", "Police")),
    new Event("Heavy Hitters", "Carson Ridge Reservoir", 17.06, "Hot Pursuit", new Tier("Speed Enforcement", "Police")),
    new Event("Highway Battle", "Carson Ridge Reservoir", 23.98, "Hot Pursuit", new Tier("Hyper", "Racer")),
    new Event("Hotting Up", "Rockhingam Point", 23.34, "Hot Pursuit", new Tier("Exotic", "Racer")),
    new Event("Point of Impact", "East Gorge Canyon", 23.34, "Hot Pursuit", new Tier("Traffic Police", "Police")),
    new Event("Porsche Patrol", "Memorial Valley", 18.51, "Hot Pursuit", new Tier("Rapid Deployment", "Police")),
    new Event("Power Struggle", "East Gorge Canyon", 19.31, "Hot Pursuit", new Tier("Exotic", "Racer")),
    new Event("Run to the Hills", "East Gorge Canyon", 18.35, "Hot Pursuit", new Tier("Rapid Deployment", "Police")),
    new Event("Shock and Awe", "Mission Beach", 17.06, "Hot Pursuit", new Tier("Performance", "Racer")),
    new Event("Snake Pit", "Rockhingam Point", 22.05, "Hot Pursuit", new Tier("Rapid Deployment", "Police")),
    new Event("Stampede", "East Gorge Canyon", 18.19, "Hot Pursuit", new Tier("Super", "Racer")),
    new Event("Summit Assault", "Eagle Crest", 20.28, "Hot Pursuit", new Tier("Highway Patrol", "Police")),
    new Event("Unreasonable Force", "Carson Ridge Reservoir", 20.76, "Hot Pursuit", new Tier("Super", "Racer")),

    new Event("Block Buster", "Grand Ocean Coast", 0.0, "Interceptor", new Tier("Traffic Police", "Police")),
    new Event("Chase 101", "Boulder Desert", 0.0, "Interceptor", new Tier("Traffic Police", "Police")),
    new Event("Denial of Service", "Coral Bay", 0.0, "Interceptor", new Tier("Highway Patrol", "Police")),
    new Event("Desert Strike", "Boulder Desert", 0.0, "Interceptor", new Tier("Speed Enforcement", "Police")),
    new Event("Double Cross", "Eagle Crest", 0.0, "Interceptor", new Tier("Special Response", "Police")),
    new Event("Eye in the Sky", "Rockhingam Point", 0.0, "Interceptor", new Tier("Highway Patrol", "Police")),
    new Event("Fight Night", "Eagle Crest", 0.0, "Interceptor", new Tier("Speed Enforcement", "Police")),
    new Event("Fighting Dirty", "Big Timber Forest", 0.0, "Interceptor", new Tier("Traffic Police", "Police")),
    new Event("Hang Tough", "Grand Ocean Coast", 0.0, "Interceptor", new Tier("Rapid Deployment", "Police")),
    new Event("Hard to Handle", "Mission Beach", 0.0, "Interceptor", new Tier("Special Response", "Police")),
    new Event("Limited Emission", "Boulder Desert", 0.0, "Interceptor", new Tier("Rapid Deployment", "Police")),
    new Event("Locking On", "Carson Ridge Reservoir", 0.0, "Interceptor", new Tier("Rapid Deployment", "Police")),
    new Event("Natural Selection", "Oakmont Valley", 0.0, "Interceptor", new Tier("Special Response", "Police")),
    new Event("Spike Out", "Memorial Valley", 0.0, "Interceptor", new Tier("Highway Patrol", "Police")),
    new Event("Takedown Notice", "Eagle Crest", 0.0, "Interceptor", new Tier("Speed Enforcement", "Police")),
    new Event("Tough Justice", "Coral Bay", 0.0, "Interceptor", new Tier("Speed Enforcement", "Police")),
    new Event("Turn the Tables", "East Gorge Canyon", 0.0, "Interceptor", new Tier("Highway Patrol", "Police")),
    new Event("Under Pressure", "Fox Lair Pass", 0.0, "Interceptor", new Tier("Rapid Deployment", "Police")),
    new Event("Weapon of Choice", "Boulder Desert", 0.0, "Interceptor", new Tier("Speed Enforcement", "Police")),

    new Event("Coming in Hot", "Carson Ridge Reservoir", 11.59, "Rapid Response", new Tier("Rapid Deployment","Police")),
    new Event("Contact Sport", "Big Timber Forest", 17.7, "Rapid Response", new Tier("Special Response","Police")),
    new Event("Damage Limitation", "Boulder Desert", 17.06, "Rapid Response", new Tier("Special Response","Police")),
    new Event("Guided Missile", "Carson Ridge Reservoir", 18.51, "Rapid Response", new Tier("Rapid Deployment","Police")),
    new Event("Lightning Reflex", "Memorial Valley", 12.87, "Rapid Response", new Tier("Traffic Police","Police")),
    new Event("More Haste, Less Speed", "Big Timber Forest", 12.23, "Rapid Response", new Tier("Highway Patrol","Police")),
    new Event("Precision Pursuit", "Memorial Valley", 9.82, "Rapid Response", new Tier("Highway Patrol","Police")),
    new Event("Priority Call", "Fox Lair Pass", 17.7, "Rapid Response", new Tier("Speed Enforcement","Police")),
    new Event("Sunset Scalpel", "Mission Beach", 16.74, "Rapid Response", new Tier("Speed Enforcement","Police")),
    new Event("Untouchable", "Boulder Desert", 18.35, "Rapid Response", new Tier("Speed Enforcement","Police")),
    
    new Event("Ageless", "Big Timber Forest", 12.55, "Preview", new Tier("Exotic","Racer")),
    new Event("Do Look After It", "Grand Ocean Coast", 8.37, "Preview", new Tier("Traffic Police","Police")),
    new Event("Extreme Truth", "Fox Lair Pass", 12.23, "Preview", new Tier("Performance","Racer")),
    new Event("French Connection", "Rockhingam Point", 8.53, "Preview", new Tier("Highway Patrol","Police")),
    new Event("Protect and Swerve", "Fox Lair Pass", 6.6, "Preview", new Tier("Highway Patrol","Police")),
    new Event("Reventón Reveal", "Coral Bay", 5.63, "Preview", new Tier("Traffic Police","Police")),
    new Event("Sand Timer", "Mission Beach", 18.35, "Preview", new Tier("Super","Racer")),
    new Event("Swedish Swoop", "Eagle Crest", 14, "Preview", new Tier("Rapid Deployment","Police")),
    new Event("The Ultimate Road Car", "Eagle Crest", 14, "Preview", new Tier("Performance","Racer")),
    new Event("Ultimately Open", "Oakmont Valley", 7.72, "Preview", new Tier("Super","Racer")),
    new Event("Unlimited Driving Pleasure", "Oakmont Valley", 10.94, "Preview", new Tier("Sports","Racer")),
    new Event("Vanishing Point", "East Gorge Canyon", 6.76, "Preview", new Tier("Sports","Racer")),
    
    new Event("Blast from the Past", "Rockhingam Point", 22.53, "Gauntlet", new Tier("Hyper Series","Racer")),
    new Event("M Power", "Memorial Valley", 11.75, "Gauntlet", new Tier("Performance Series","Racer")),
    new Event("One of Five", "Oakmont Valley", 13.2, "Gauntlet", new Tier("Exotic Series","Racer")),
    new Event("Tough Torque", "Oakmont Valley", 19.63, "Gauntlet", new Tier("Exotic Series","Racer")),
    new Event("Trail of Destruction", "Oakmont Valley", 13.36, "Gauntlet", new Tier("Super Series","Racer")),
    
    new Event("Complete Control", "Fox Lair Pass", 14.65, "Duel", new Tier("Performance","Racer")),
    new Event("Heart to Heart", "Coral Bay", 16.25, "Duel", new Tier("Super","Racer")),
    new Event("King of the Road", "Rockhingam Point", 22.69, "Duel", new Tier("Hyper","Racer")),
    new Event("Power Trip", "Coral Bay", 10.94, "Duel", new Tier("Super","Racer")),
    new Event("Racing Stripes", "Eagle Crest", 20.12, "Duel", new Tier("Super","Racer")),
    new Event("Spirit of Performance", "Carson Ridge Reservoir", 10.78, "Duel", new Tier("Hyper","Racer")),
    new Event("The Art of Driving", "Fox Lair Pass", 20.12, "Duel", new Tier("Exotic","Racer")),
    new Event("Title Fight", "Big Timber Forest", 11.27, "Duel", new Tier("Sports","Racer")),
    new Event("Twin Turbo", "Mission Beach", 17.38, "Duel", new Tier("Exotic","Racer")),

    new Event("Born in the USA", "Boulder Desert", 17.06, "Race", new Tier("Exotic","Racer")),
    new Event("Coast to Coast", "Grand Ocean Coast", 19.79, "Race", new Tier("Super","Racer")),
    new Event("Encore Performance", "Carson Ridge Reservoir", 17.06, "Race", new Tier("Performance","Racer")),
    new Event("Faster Than Light", "Boulder Desert", 23.34, "Race", new Tier("Hyper","Racer")),
    new Event("Future Perfect", "Carson Ridge Reservoir", 21.24, "Race", new Tier("Sports","Racer")),
    new Event("Glorious Fourth", "Fox Lair Pass", 11.75, "Race", new Tier("Exotic","Racer")),
    new Event("Jet Stream", "East Gorge Canyon", 12.71, "Race", new Tier("Exotic","Racer")),
    new Event("Muscle Reflex", "Boulder Desert", 11.59, "Race", new Tier("Performance","Racer")),
    new Event("No Substitute", "Memorial Valley", 12.07, "Race", new Tier("Super","Racer")),
    new Event("Passione Italia", "Boulder Desert", 17.86, "Race", new Tier("Exotic","Racer")),
    new Event("Roadsters Reborn", "Grand Ocean Coast", 13.52, "Race", new Tier("Sports","Racer")),
    new Event("Seacrest Tour", "Coral Bay", 70.01, "Race", new Tier("Hyper","Racer")),
    new Event("Spoilt for Choice", "Memorial Valley", 19.31, "Race", new Tier("Exotic","Racer")),
    new Event("Sports Car Named Desire", "Eagle Crest", 10.78, "Race", new Tier("Sports","Racer")),
    new Event("Sun, Sand and Supercars", "Boulder Desert", 18.35, "Race", new Tier("Performance","Racer")),
    new Event("The Prestige", "Big Timber Forest", 21.24, "Race", new Tier("Performance","Racer")),

    new Event("Bull Run", "Big Timber Forest", 15.13, "Time Trial", new Tier("Exotic","Racer")),
    new Event("Experience More", "Rockhingam Point", 6.44, "Time Trial", new Tier("Performance","Racer")),
    new Event("Sidewinder", "Memorial Valley", 6.76, "Time Trial", new Tier("Performance","Racer")),
    new Event("Slide Show", "Big Timber Forest", 13.52, "Time Trial", new Tier("Exotic","Racer")),
    new Event("Timed Machine", "Eagle Crest", 13.2, "Time Trial", new Tier("Super","Racer")),
    new Event("V12 for Victory", "Grand Ocean Coast", 6.76, "Time Trial", new Tier("Super","Racer")),
    new Event("Wild Ride", "Carson Ridge Reservoir", 14, "Time Trial", new Tier("Hyper","Racer")),

];